# Generated by Django 3.1.5 on 2021-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210528_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(verbose_name=[(0, 'Text'), (1, 'Link'), (2, 'Photo')]),
        ),
    ]
