# Generated by Django 3.1.5 on 2021-06-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210605_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
