# Generated by Django 3.1.5 on 2021-04-11 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 4, 11, 19, 46, 36, 687150))),
                ('banner', models.URLField(blank=True)),
                ('uuid', models.UUIDField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_groups', to='users.profile')),
                ('members', models.ManyToManyField(related_name='joined_groups', to='users.Profile')),
            ],
        ),
    ]
