# Generated by Django 3.1.5 on 2021-04-11 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
