# Generated by Django 3.1.5 on 2021-04-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(default='123e4567-e89b-12d3-a456-426614174000'),
            preserve_default=False,
        ),
    ]
